### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by masad-frost** [lezer-parser/python#10]
More specifically the match..case syntax, it seems to be break the parser

Here's an example on Replit 
![](https://user-images.githubusercontent.com/1994028/181029414-a7256a80-8c70-47e5-924b-11eae4b7fc66.png)

```py
def http_status(status):
  match status:
    case 400:
      return "Bad request"
    case 401 | 403:
      return "Authentication error"
    case 404:
      return "Not found"
    case _:
      return "Unknown error"
```

**Comment by marijnh** [comment]
@lezer/python 1.1.0 should add this.
