### ISSUE TITLE
Newline breaks and special characters break string in an edge-case

### ISSUE THREAD

**Issue by yuriymironov96** [lezer-parser/python#16]
Hi! First things first, this is a great package and we had zero issues with it for more than a year, thanks a lot for it!

We stumbled into an edge-case though. We are creating an app that works with Python scripts, and these scripts support an extra bit of custom syntax. Here is how it looks:

```
def foo():
    return 'My string'!A1:B1

```

The idea behind this is, `'My string'` is a valid Python string, and `!` is a property accessor of some sort. Pretty much like `.` in `obj.property`.

As you can see, it works in other environments (like VS Code). Yes, there are errors, but we do the interpreting on our side, and only need a proper code highlight.

<img width="280" alt="image" src="https://github.com/lezer-parser/python/assets/20914261/a68a66fb-815a-42eb-9afd-54891ff95b61">

But with lezer-parser/python it looks as follows:

<img width="318" alt="image" src="https://github.com/lezer-parser/python/assets/20914261/4b6a0487-1075-4a01-8283-42263fa975f8">

However, the following snippets are highlighted properly:

(without whitespace)
```
def foo():
    return 'My string'!A1:B1
```
<img width="303" alt="image" src="https://github.com/lezer-parser/python/assets/20914261/49e3aa05-6cf7-4be3-b063-60f478d5db63">

(without colon)
```
def foo():
    return 'My string'!A1B1
```
<img width="327" alt="image" src="https://github.com/lezer-parser/python/assets/20914261/f15e3be8-d8a5-492a-b14d-0704e6fa6c9a">

I do realise this is not an issue Python users suffer from, since this code will not compile. Is this something worth fixing in the main package, or should I fork it since we have our custom syntax?

**Comment by marijnh** [comment]
This library provides no particular guarantees on how it parses invalid input. Here it seems to have decided that, since `!` isn't a valid token in regular Python context, the best thing it can do is insert a `"` token and continue parsing the rest of the input as a string. Which is pretty ingenious, though I guess not what you were hoping for here.
