### ISSUE TITLE
Support type argument syntax PEP 695 (Python 3.12)

### ISSUE THREAD

**Issue by masad-frost** [lezer-parser/python#19]
there's a new type argument syntax for functions and classes

```py
def max[T](args: Iterable[T]) -> T:
    pass

class list[T]:
    def __getitem__(self, index: int, /) -> T:
        pass

    def append(self, element: T) -> None:
        pass
```

Resources:
- https://docs.python.org/3/reference/compound_stmts.html#generic-classes
- https://docs.python.org/3/reference/compound_stmts.html#generic-functions
- https://peps.python.org/pep-0695/
- https://docs.python.org/3/whatsnew/3.12.html#whatsnew312-pep695
- Related issue: #18 

See also screenshot in [lezer playground](https://lezer-playground.replit.app/) by @dralletje, this completely throws off the parser (it thinks it's an array, and it breaks down). 

![image](https://github.com/lezer-parser/python/assets/1994028/021245ec-e3a3-4fd7-9086-5dcd159f3daa)

I must say I'm impressed by CM+Lezer at how very well everything recovers.

**Comment by masad-frost** [comment]
Issue is not very pressing given how well the parser seems to recover after a bit.

**Comment by iahu** [comment]
the latest `@codemirror/lang-python` still not highlight python type

<img width="362" alt="image" src="https://github.com/user-attachments/assets/eed8eb73-60d4-4785-be3e-a117d4461c06">

**Comment by marijnh** [comment]
Types are just expressions in Python, which is why we're highlighting them like regular expressions.
