### ISSUE TITLE
Parsing of f-string with `=`

### ISSUE THREAD

**Issue by fcollonval** [lezer-parser/python#21]
The f-strings containing `=` for self-documenting expressions are not parsed correctly:

![image](https://github.com/lezer-parser/python/assets/8435071/32dbf5fc-cb6e-45ec-a192-309a866458bf)

Using `"@lezer/python@1.1.7`

The related python feature is described there: https://docs.python.org/3/whatsnew/3.8.html#bpo-36817-whatsnew

**Comment by marijnh** [comment]
Attached patch adds this syntax
