### ISSUE TITLE
bug: syntax error if python code ends with line comment

### ISSUE THREAD

**Issue by Entkenntnis** [lezer-parser/python#25]
I'm attempting to parse this code:

![grafik](https://github.com/lezer-parser/python/assets/13507950/c59a2512-8689-42a0-a66d-3dbc1461cc69)

Unexpectedly, there is a syntax error at the end of the document. The AST looks like this:

![grafik](https://github.com/lezer-parser/python/assets/13507950/33c83004-680a-45cd-b187-5984042c0cbd)

If I add a new line, the code becomes valid:

![grafik](https://github.com/lezer-parser/python/assets/13507950/51609ff4-a961-46e3-8577-3ee42d4e5a5c)

version: lezer-parser/python 1.1.14

**Comment by marijnh** [comment]
Attached patch should address this.
