### ISSUE TITLE
Bug in newline tokenizer?

### ISSUE THREAD

**Issue by dougmartin** [lezer-parser/python#4]
I was looking at the newline tokenizer to understand how to parse an indentation significant language and I'm wondering if there is a bug on this line:

`else if (ch == newline || indent == carriageReturn || ch == hash) {`

(https://github.com/lezer-parser/python/blob/master/src/tokens.js#L99)

it seems it should be this instead:

`else if (ch == newline || ch == carriageReturn || ch == hash) {`

I'd be happy to open a PR if it is a bug to help resolve it.  I wanted to check first though.

**Comment by marijnh** [comment]
Thanks --- I had noticed the same thing last week but hadn't pushed my patch (05a7310df15b) yet.
