### ISSUE TITLE
Minor issue with indentation

### ISSUE THREAD

**Issue by R167** [lezer-parser/python#7]
Noticed a funny quirk now with indentation. The parser _usually_ handles consistent leading indentation correctly, but fails in a few instances, for example:

```python
# Note the initial 4 space indent
    if False:
        print("hi")
    else:
        print("bye")
```

Trying to run this program using python results in a syntax error (since it doesn't support extraneous leading indentation).

Interestingly, this parse error only appears to occur in followup blocks, e.g. the following still parses without error

```python
# Also note initial indentation (GitHub code blocks don't show this the best).
  class C(object):
    def f(self: C) -> int:
      if True:
        return 0
      else:
        1
    def other():
      pass
```

The cleanest approach may be to enforce the first statement starts with no indentation as is expected by python?

(To be clear,  both code blocks parsed in 0.13.5, but only the second one still does in 0.13.6. Based on the python spec, I would expect neither to parse correctly)

**Comment by marijnh** [comment]
Since real error checking is outside of the scope of Lezer parsers, and the problem appears to be that it accepts some programs that aren't actually valid, I'm going to say that this is out of scope. (The underlying problem appears to be that indentation context is only updated when an indent or dedent token is successfully shifted, which just doesn't happen for some invalid indentations—but should happen for all valid indentation changes.)

**Comment by R167** [comment]
Sounds reasonable, and thanks for taking a quick look at root cause. Given how painful Python's indentation can be and how it's changed from 2.x to 3.x as well, I agree being able to validate all legal and let slide some illegal programs is fine.

**Comment by marijnh** [comment]
> and how it's changed from 2.x to 3.x as well,

Indentation rules changed? I just implemented the 3.x rules. What were the differences?

**Comment by R167** [comment]
There's some pretty odd edge cases about how mixed indentation (tabs and spaces and how it resolved the lexed indentation level) is determined. For example, the follow program is legal in python 2, but fails with TabError in python 3.

```python
def hi():
 if False:
   print("hi")
 else:
  	print("bye")
 	print("bad")

hi()
```
(screenshot showing invisible characters)
![image](https://user-images.githubusercontent.com/4950148/109038894-116ac200-7681-11eb-8ed9-c220bec8d535.png)

If I remember correctly it harks back to an odd way lexing tabs was implemented in the python 2 lexer which they resolved in python 3. Almost thought I was crazy for a sec because I didn't see it mentioned in any of the syntax change logs, but yup, that was a strange thing python 2 did.
